// Spelling Quest word bank
//   w = word, s = syllables, m = meaning, e = example sentence, lv = level (1-4)
//   t = (optional) hand-picked "trap" letter positions for the Missing Letters game
// Level 1-2 include the UK National Curriculum Year 3-4 / Year 5-6 statutory
// spelling lists (US spelling). Level 3 = school subjects, Level 4 = challenge.
// After adding words, run  python gen_audio.py  to make their MP3s.
const WORD_BANK = [
  {"w":"February","s":["Feb","ru","ar","y"],"m":"the 2nd month","e":"My birthday is in February.","lv":1,"t":[3]},
  {"w":"separate","s":["sep","a","rate"],"m":"to divide; apart","e":"Separate the recycling.","lv":1,"t":[3]},
  {"w":"beautiful","s":["beau","ti","ful"],"m":"very pretty","e":"That's a beautiful painting.","lv":1,"t":[1,2,3]},
  {"w":"similar","s":["sim","i","lar"],"m":"alike; almost the same","e":"Their backpacks are similar.","lv":1,"t":[3,5,6]},
  {"w":"calendar","s":["cal","en","dar"],"m":"chart of days/months","e":"Check the calendar for the date.","lv":1,"t":[3,7]},
  {"w":"vegetable","s":["veg","e","ta","ble"],"m":"a plant we eat","e":"Eat your vegetables.","lv":1,"t":[3]},
  {"w":"character","s":["char","ac","ter"],"m":"a person in a story","e":"Harry Potter is the main character.","lv":1,"t":[1]},
  {"w":"exercise","s":["ex","er","cise"],"m":"physical activity","e":"Exercise keeps you healthy.","lv":1,"t":[3,4,5]},
  {"w":"occasionally","s":["oc","ca","sion","al","ly"],"m":"sometimes","e":"I occasionally eat dessert.","lv":1,"t":[1,7]},
  {"w":"interesting","s":["in","ter","est","ing"],"m":"holding your attention","e":"That book is really interesting.","lv":1,"t":[3,4]},
  {"w":"different","s":["dif","fer","ent"],"m":"not the same","e":"We have different opinions.","lv":1,"t":[3,5]},
  {"w":"probably","s":["prob","a","bly"],"m":"most likely","e":"It will probably rain.","lv":1,"t":[4]},
  {"w":"usually","s":["u","su","al","ly"],"m":"most of the time","e":"I usually walk to school.","lv":1,"t":[3,4]},
  {"w":"attention","s":["at","ten","tion"],"m":"focus or notice","e":"Pay attention in class.","lv":1,"t":[1]},
  {"w":"position","s":["po","si","tion"],"m":"place or location","e":"What position do you play?","lv":1},
  {"w":"comfortable","s":["com","fort","a","ble"],"m":"feeling at ease","e":"This chair is comfortable.","lv":1,"t":[7]},
  {"w":"president","s":["pres","i","dent"],"m":"the leader of a country","e":"The president lives in the White House.","lv":1,"t":[4]},
  {"w":"tomorrow","s":["to","mor","row"],"m":"the day after today","e":"See you tomorrow!","lv":1,"t":[1,3,4]},
  {"w":"opposite","s":["op","po","site"],"m":"completely different","e":"Hot is the opposite of cold.","lv":1,"t":[1,2,5]},
  {"w":"furniture","s":["fur","ni","ture"],"m":"chairs, tables, beds","e":"We bought new furniture.","lv":1,"t":[4,6]},
  {"w":"interview","s":["in","ter","view"],"m":"a meeting to ask questions","e":"I have a job interview.","lv":1},
  {"w":"introduce","s":["in","tro","duce"],"m":"to present someone for the first time","e":"Let me introduce my friend.","lv":1,"t":[6,7]},
  {"w":"understand","s":["un","der","stand"],"m":"to get the meaning","e":"I understand the directions.","lv":1},
  {"w":"experience","s":["ex","pe","ri","ence"],"m":"something you've done","e":"Tell me about your experience.","lv":1,"t":[5,7,8]},
  {"w":"continue","s":["con","tin","ue"],"m":"to keep going","e":"Please continue your story.","lv":1,"t":[6,7]},
  {"w":"disappear","s":["dis","ap","pear"],"m":"to go out of sight","e":"The magician made the rabbit disappear.","lv":1},
  {"w":"favorite","s":["fa","vor","ite"],"m":"liked more than others","e":"Pizza is my favorite food.","lv":1},
  {"w":"grammar","s":["gram","mar"],"m":"the rules of how to use a language","e":"Good grammar is important.","lv":1},
  {"w":"experiment","s":["ex","per","i","ment"],"m":"a scientific test","e":"We did an experiment in class.","lv":1},
  {"w":"particular","s":["par","tic","u","lar"],"m":"specific or exact","e":"Is there a particular book you want?","lv":1},
  {"w":"adventure","s":["ad","ven","ture"],"m":"an exciting experience","e":"Their trip was a real adventure.","lv":1},
  {"w":"apology","s":["a","pol","o","gy"],"m":"a statement of regret","e":"Please accept my apology.","lv":1},
  {"w":"battery","s":["bat","ter","y"],"m":"a device that stores energy","e":"My phone battery is dead.","lv":1},
  {"w":"citizen","s":["cit","i","zen"],"m":"a member of a country","e":"Every citizen has rights.","lv":1},
  {"w":"collection","s":["col","lec","tion"],"m":"a group of things gathered","e":"She has a stamp collection.","lv":1},
  {"w":"comedy","s":["com","e","dy"],"m":"a funny play or movie","e":"We watched a comedy last night.","lv":1},
  {"w":"consider","s":["con","sid","er"],"m":"to think about carefully","e":"Please consider my offer.","lv":1},
  {"w":"customer","s":["cus","to","mer"],"m":"a person who buys goods","e":"The customer is always right.","lv":1},
  {"w":"delivery","s":["de","liv","er","y"],"m":"the act of bringing something","e":"The delivery arrived on time.","lv":1},
  {"w":"discover","s":["dis","cov","er"],"m":"to find something new","e":"They discovered a new island.","lv":1},
  {"w":"accident","s":["ac","ci","dent"],"m":"something bad that happens by chance","e":"I broke the cup by accident.","lv":1},
  {"w":"actually","s":["ac","tu","al","ly"],"m":"in fact; really","e":"Actually, I like broccoli.","lv":1},
  {"w":"address","s":["ad","dress"],"m":"where someone lives","e":"Write your address on the envelope.","lv":1},
  {"w":"answer","s":["an","swer"],"m":"a reply to a question","e":"Do you know the answer?","lv":1},
  {"w":"appear","s":["ap","pear"],"m":"to come into sight","e":"Stars appear at night.","lv":1},
  {"w":"arrive","s":["ar","rive"],"m":"to reach a place","e":"We will arrive at noon.","lv":1},
  {"w":"believe","s":["be","lieve"],"m":"to think something is true","e":"I believe you.","lv":1},
  {"w":"bicycle","s":["bi","cy","cle"],"m":"a bike with two wheels","e":"I ride my bicycle to the park.","lv":1},
  {"w":"breath","s":["breath"],"m":"the air you take in","e":"Take a deep breath.","lv":1},
  {"w":"breathe","s":["breathe"],"m":"to take air in and out","e":"Fish breathe underwater.","lv":1},
  {"w":"build","s":["build"],"m":"to make something by putting parts together","e":"Let's build a sandcastle.","lv":1},
  {"w":"busy","s":["bus","y"],"m":"having lots to do","e":"Mom is busy today.","lv":1},
  {"w":"business","s":["bus","i","ness"],"m":"buying and selling; a company","e":"My uncle runs a small business.","lv":1},
  {"w":"caught","s":["caught"],"m":"grabbed; past of catch","e":"I caught the ball!","lv":1},
  {"w":"center","s":["cen","ter"],"m":"the middle","e":"Stand in the center of the circle.","lv":1},
  {"w":"century","s":["cen","tu","ry"],"m":"100 years","e":"This house is a century old.","lv":1},
  {"w":"certain","s":["cer","tain"],"m":"sure","e":"I'm certain it will rain.","lv":1},
  {"w":"circle","s":["cir","cle"],"m":"a round shape","e":"Draw a circle.","lv":1},
  {"w":"complete","s":["com","plete"],"m":"finished; whole","e":"Complete your homework first.","lv":1},
  {"w":"decide","s":["de","cide"],"m":"to make a choice","e":"I can't decide which ice cream to get.","lv":1},
  {"w":"describe","s":["de","scribe"],"m":"to tell what something is like","e":"Describe your best friend.","lv":1},
  {"w":"difficult","s":["dif","fi","cult"],"m":"hard to do","e":"This puzzle is difficult.","lv":1},
  {"w":"early","s":["ear","ly"],"m":"before the usual time","e":"I woke up early.","lv":1},
  {"w":"earth","s":["earth"],"m":"the planet we live on","e":"The earth goes around the sun.","lv":1},
  {"w":"eight","s":["eight"],"m":"the number 8","e":"A spider has eight legs.","lv":1},
  {"w":"eighth","s":["eighth"],"m":"number 8 in order","e":"It's my eighth birthday.","lv":1},
  {"w":"enough","s":["e","nough"],"m":"as much as needed","e":"Do we have enough pizza?","lv":1},
  {"w":"extreme","s":["ex","treme"],"m":"very great or very strong","e":"Extreme heat can be dangerous.","lv":1},
  {"w":"famous","s":["fa","mous"],"m":"known by many people","e":"She is a famous singer.","lv":1},
  {"w":"forward","s":["for","ward"],"m":"toward the front","e":"Take one step forward.","lv":1},
  {"w":"fruit","s":["fruit"],"m":"food like apples and bananas","e":"Fruit is a healthy snack.","lv":1},
  {"w":"group","s":["group"],"m":"people or things together","e":"Work in a group of four.","lv":1},
  {"w":"guard","s":["guard"],"m":"to protect; a person who protects","e":"The dog guards the house.","lv":1},
  {"w":"guide","s":["guide"],"m":"to show the way","e":"Our guide showed us the museum.","lv":1},
  {"w":"heard","s":["heard"],"m":"past of hear","e":"I heard a strange noise.","lv":1},
  {"w":"heart","s":["heart"],"m":"the organ that pumps blood","e":"My heart beats fast when I run.","lv":1},
  {"w":"height","s":["height"],"m":"how tall something is","e":"What is your height?","lv":1},
  {"w":"history","s":["his","to","ry"],"m":"the story of the past","e":"We learned about history today.","lv":1},
  {"w":"imagine","s":["i","mag","ine"],"m":"to picture in your mind","e":"Imagine you can fly.","lv":1},
  {"w":"increase","s":["in","crease"],"m":"to make bigger","e":"The noise will increase.","lv":1},
  {"w":"important","s":["im","por","tant"],"m":"mattering a lot","e":"Sleep is important.","lv":1},
  {"w":"interest","s":["in","ter","est"],"m":"wanting to know more","e":"I have an interest in dinosaurs.","lv":1},
  {"w":"island","s":["is","land"],"m":"land with water all around","e":"We sailed to an island.","lv":1},
  {"w":"knowledge","s":["knowl","edge"],"m":"what you know","e":"Books give us knowledge.","lv":1},
  {"w":"learn","s":["learn"],"m":"to find out something new","e":"I learn new words every day.","lv":1},
  {"w":"length","s":["length"],"m":"how long something is","e":"Measure the length of the table.","lv":1},
  {"w":"library","s":["li","brar","y"],"m":"a place with books to borrow","e":"I borrowed a book from the library.","lv":1},
  {"w":"material","s":["ma","te","ri","al"],"m":"what something is made of","e":"Cotton is a soft material.","lv":1},
  {"w":"medicine","s":["med","i","cine"],"m":"something that makes you better","e":"Take your medicine.","lv":1},
  {"w":"mention","s":["men","tion"],"m":"to talk about briefly","e":"Did she mention the party?","lv":1},
  {"w":"minute","s":["min","ute"],"m":"60 seconds","e":"Wait a minute!","lv":1},
  {"w":"natural","s":["nat","u","ral"],"m":"made by nature","e":"Rivers are natural.","lv":1},
  {"w":"naughty","s":["naugh","ty"],"m":"badly behaved","e":"The naughty puppy chewed my shoe.","lv":1},
  {"w":"notice","s":["no","tice"],"m":"to see or pay attention to","e":"Did you notice my new haircut?","lv":1},
  {"w":"occasion","s":["oc","ca","sion"],"m":"a special event or time","e":"A wedding is a special occasion.","lv":1},
  {"w":"often","s":["of","ten"],"m":"many times","e":"I often read before bed.","lv":1},
  {"w":"ordinary","s":["or","di","nar","y"],"m":"normal; not special","e":"It was an ordinary day.","lv":1},
  {"w":"peculiar","s":["pe","cu","liar"],"m":"strange; odd","e":"What a peculiar smell!","lv":1},
  {"w":"perhaps","s":["per","haps"],"m":"maybe","e":"Perhaps it will snow tomorrow.","lv":1},
  {"w":"popular","s":["pop","u","lar"],"m":"liked by many people","e":"Soccer is a popular sport.","lv":1},
  {"w":"possess","s":["pos","sess"],"m":"to own","e":"Do you possess a library card?","lv":1},
  {"w":"possession","s":["pos","ses","sion"],"m":"something you own","e":"This bike is my favorite possession.","lv":1},
  {"w":"possible","s":["pos","si","ble"],"m":"able to happen","e":"Is it possible to visit the moon?","lv":1},
  {"w":"potatoes","s":["po","ta","toes"],"m":"more than one potato","e":"I love mashed potatoes.","lv":1},
  {"w":"pressure","s":["pres","sure"],"m":"a pushing force","e":"Press with gentle pressure.","lv":1},
  {"w":"promise","s":["prom","ise"],"m":"to say you will surely do something","e":"I promise to be home by six.","lv":1},
  {"w":"purpose","s":["pur","pose"],"m":"the reason for something","e":"What is the purpose of this button?","lv":1},
  {"w":"quarter","s":["quar","ter"],"m":"one of four equal parts","e":"Cut the apple into quarters.","lv":1},
  {"w":"question","s":["ques","tion"],"m":"something you ask","e":"Can I ask a question?","lv":1},
  {"w":"recent","s":["re","cent"],"m":"happening not long ago","e":"This is a recent photo.","lv":1},
  {"w":"regular","s":["reg","u","lar"],"m":"normal; happening often","e":"Regular exercise keeps you fit.","lv":1},
  {"w":"reign","s":["reign"],"m":"to rule as king or queen","e":"The queen's reign was long.","lv":1},
  {"w":"remember","s":["re","mem","ber"],"m":"to keep in your mind","e":"Remember to bring your lunch.","lv":1},
  {"w":"sentence","s":["sen","tence"],"m":"a group of words that makes sense","e":"Write a sentence with this word.","lv":1},
  {"w":"special","s":["spe","cial"],"m":"different and important","e":"Today is a special day.","lv":1},
  {"w":"straight","s":["straight"],"m":"not bent or curved","e":"Draw a straight line.","lv":1},
  {"w":"strange","s":["strange"],"m":"unusual; odd","e":"I heard a strange sound.","lv":1},
  {"w":"strength","s":["strength"],"m":"how strong you are","e":"It takes strength to lift that.","lv":1},
  {"w":"suppose","s":["sup","pose"],"m":"to think or guess","e":"I suppose you're right.","lv":1},
  {"w":"surprise","s":["sur","prise"],"m":"something you didn't expect","e":"We threw a surprise party.","lv":1},
  {"w":"therefore","s":["there","fore"],"m":"for that reason","e":"It rained; therefore, we stayed inside.","lv":1},
  {"w":"though","s":["though"],"m":"however; even if","e":"It was cold, though sunny.","lv":1},
  {"w":"although","s":["al","though"],"m":"even though","e":"Although I was tired, I finished.","lv":1},
  {"w":"thought","s":["thought"],"m":"an idea; past of think","e":"I thought about you.","lv":1},
  {"w":"through","s":["through"],"m":"in one side and out the other","e":"We walked through the forest.","lv":1},
  {"w":"various","s":["var","i","ous"],"m":"different kinds","e":"The store sells various toys.","lv":1},
  {"w":"weight","s":["weight"],"m":"how heavy something is","e":"What is the weight of this box?","lv":1},
  {"w":"woman","s":["wom","an"],"m":"an adult female","e":"The woman smiled at me.","lv":1},
  {"w":"women","s":["wom","en"],"m":"more than one woman","e":"Three women joined the team.","lv":1},
  {"w":"because","s":["be","cause"],"m":"for the reason that","e":"I stayed home because I was sick.","lv":1},
  {"w":"friend","s":["friend"],"m":"a person you like and trust","e":"She is my best friend.","lv":1},
  {"w":"beginning","s":["be","gin","ning"],"m":"the start","e":"Read it from the beginning.","lv":1},
  {"w":"receive","s":["re","ceive"],"m":"to get something","e":"Did you receive my letter?","lv":1},
  {"w":"piece","s":["piece"],"m":"a part of something","e":"Can I have a piece of cake?","lv":1},
  {"w":"science","s":["sci","ence"],"m":"the study of how the world works","e":"Science is my favorite subject.","lv":1},
  {"w":"laugh","s":["laugh"],"m":"to make sounds when something is funny","e":"The joke made me laugh.","lv":1},
  {"w":"weird","s":["weird"],"m":"very strange","e":"That's a weird bug!","lv":1},
  {"w":"Wednesday","s":["Wednes","day"],"m":"the day after Tuesday","e":"We have swimming on Wednesday.","lv":1},
  {"w":"tongue","s":["tongue"],"m":"the part of your mouth that tastes","e":"Stick out your tongue.","lv":1},
  {"w":"necessary","s":["nec","es","sar","y"],"m":"needed; required","e":"Sleep is necessary for health.","lv":2,"t":[2,4,5]},
  {"w":"definitely","s":["def","i","nite","ly"],"m":"for sure; without doubt","e":"I will definitely come.","lv":2,"t":[3,5]},
  {"w":"restaurant","s":["res","tau","rant"],"m":"a place to eat","e":"We ate at a Mexican restaurant.","lv":2,"t":[3,4,5]},
  {"w":"government","s":["gov","ern","ment"],"m":"the people who run a country","e":"The government makes laws.","lv":2,"t":[3,4]},
  {"w":"environment","s":["en","vi","ron","ment"],"m":"the natural world","e":"We must protect the environment.","lv":2,"t":[3,5,8]},
  {"w":"embarrass","s":["em","bar","rass"],"m":"to feel shy or ashamed","e":"Don't embarrass me!","lv":2,"t":[3,4,6,7]},
  {"w":"immediately","s":["im","me","di","ate","ly"],"m":"right now","e":"Call me immediately if there's a problem.","lv":2,"t":[1,2]},
  {"w":"especially","s":["es","pe","cial","ly"],"m":"more than other things","e":"I love fruit, especially mangos.","lv":2,"t":[3]},
  {"w":"accommodate","s":["ac","com","mo","date"],"m":"to make room for","e":"The hotel can accommodate 200 guests.","lv":2,"t":[1,3,4]},
  {"w":"occurrence","s":["oc","cur","rence"],"m":"a thing that happens","e":"Earthquakes are a rare occurrence here.","lv":2,"t":[1,3,4]},
  {"w":"temperature","s":["tem","per","a","ture"],"m":"how hot or cold","e":"What's the temperature today?","lv":2,"t":[4,6]},
  {"w":"equipment","s":["e","quip","ment"],"m":"tools or gear","e":"We need the right equipment.","lv":2,"t":[2]},
  {"w":"emergency","s":["e","mer","gen","cy"],"m":"a sudden serious event","e":"Call 911 in an emergency.","lv":2},
  {"w":"dictionary","s":["dic","tion","ar","y"],"m":"book of word meanings","e":"Look it up in the dictionary.","lv":2,"t":[5,8]},
  {"w":"communicate","s":["com","mu","ni","cate"],"m":"to share information","e":"We communicate by text.","lv":2,"t":[1,2]},
  {"w":"acknowledge","s":["ac","knowl","edge"],"m":"to admit or accept as true","e":"I acknowledge my mistake.","lv":2},
  {"w":"accomplish","s":["ac","com","plish"],"m":"to succeed in doing","e":"We can accomplish anything.","lv":2},
  {"w":"atmosphere","s":["at","mos","phere"],"m":"the air around the earth","e":"The atmosphere was festive.","lv":2},
  {"w":"category","s":["cat","e","go","ry"],"m":"a group of things","e":"What category is this in?","lv":2},
  {"w":"committee","s":["com","mit","tee"],"m":"a group of people chosen for a task","e":"The committee meets on Monday.","lv":2},
  {"w":"community","s":["com","mu","ni","ty"],"m":"a group of people living in the same place","e":"Our community is very kind.","lv":2},
  {"w":"conscience","s":["con","science"],"m":"inner sense of right and wrong","e":"My conscience is clear.","lv":2},
  {"w":"decision","s":["de","ci","sion"],"m":"a choice you make","e":"It was a hard decision.","lv":2},
  {"w":"description","s":["de","scrip","tion"],"m":"words that tell what something is like","e":"Write a description of your room.","lv":2},
  {"w":"disappoint","s":["dis","ap","point"],"m":"to make someone sad by not doing what was hoped","e":"I don't want to disappoint you.","lv":2},
  {"w":"education","s":["ed","u","ca","tion"],"m":"the process of teaching and learning","e":"Education is very important.","lv":2},
  {"w":"excellent","s":["ex","cel","lent"],"m":"very good; of the highest quality","e":"She did an excellent job.","lv":2},
  {"w":"familiar","s":["fa","mil","iar"],"m":"well-known; often seen","e":"That song sounds familiar.","lv":2},
  {"w":"guarantee","s":["guar","an","tee"],"m":"a promise that something will happen","e":"I guarantee you'll like it.","lv":2},
  {"w":"hygiene","s":["hy","giene"],"m":"conditions that keep you healthy","e":"Good hygiene prevents illness.","lv":2},
  {"w":"imagination","s":["i","mag","i","na","tion"],"m":"the ability to form new ideas","e":"Use your imagination!","lv":2},
  {"w":"incredible","s":["in","cred","i","ble"],"m":"impossible or very hard to believe","e":"The view was incredible!","lv":2},
  {"w":"information","s":["in","for","ma","tion"],"m":"facts or details about something","e":"Can I have more information?","lv":2},
  {"w":"competition","s":["com","pe","ti","tion"],"m":"a contest between people","e":"The competition was fierce.","lv":2},
  {"w":"explanation","s":["ex","pla","na","tion"],"m":"a statement that makes something clear","e":"Can you give me an explanation?","lv":2},
  {"w":"pronunciation","s":["pro","nun","ci","a","tion"],"m":"the way a word is spoken","e":"Her pronunciation is very clear.","lv":2},
  {"w":"appreciate","s":["ap","pre","ci","ate"],"m":"to value or be grateful for something","e":"I appreciate your help.","lv":2},
  {"w":"exaggerate","s":["ex","ag","ger","ate"],"m":"to make something seem larger than it is","e":"Don't exaggerate the danger.","lv":2},
  {"w":"privilege","s":["priv","i","lege"],"m":"a special right or advantage","e":"Education is a privilege, not a right.","lv":2},
  {"w":"achievement","s":["a","chieve","ment"],"m":"something done successfully","e":"Winning was a great achievement.","lv":2},
  {"w":"apparent","s":["ap","par","ent"],"m":"seeming real but not proven","e":"It was apparent she was tired.","lv":2},
  {"w":"argument","s":["ar","gu","ment"],"m":"a reason or debate","e":"They had an argument.","lv":2},
  {"w":"available","s":["a","vail","a","ble"],"m":"ready to be used","e":"Is this book available?","lv":2},
  {"w":"celebrity","s":["ce","leb","ri","ty"],"m":"a famous person","e":"Many celebrities attended the event.","lv":2},
  {"w":"ceremony","s":["cer","e","mo","ny"],"m":"a formal event","e":"The graduation ceremony was lovely.","lv":2},
  {"w":"charity","s":["char","i","ty"],"m":"giving to those in need","e":"She donated to charity.","lv":2},
  {"w":"completely","s":["com","plete","ly"],"m":"totally or fully","e":"I completely agree with you.","lv":2},
  {"w":"confident","s":["con","fi","dent"],"m":"sure of yourself","e":"She is confident about the test.","lv":2},
  {"w":"controversy","s":["con","tro","ver","sy"],"m":"a public disagreement","e":"The decision caused controversy.","lv":2},
  {"w":"develop","s":["de","vel","op"],"m":"to grow or make something","e":"They develop new software.","lv":2},
  {"w":"document","s":["doc","u","ment"],"m":"a written record","e":"Please sign this document.","lv":2},
  {"w":"dramatic","s":["dra","mat","ic"],"m":"sudden or striking","e":"There was a dramatic change.","lv":2},
  {"w":"electric","s":["e","lec","tric"],"m":"using electricity","e":"We bought an electric car.","lv":2},
  {"w":"emotion","s":["e","mo","tion"],"m":"a strong feeling","e":"Joy is a powerful emotion.","lv":2},
  {"w":"accompany","s":["ac","com","pa","ny"],"m":"to go with someone","e":"I'll accompany you to the store.","lv":2},
  {"w":"according","s":["ac","cord","ing"],"m":"as said by","e":"According to the map, we're close.","lv":2},
  {"w":"achieve","s":["a","chieve"],"m":"to succeed in doing","e":"You can achieve your goals.","lv":2},
  {"w":"aggressive","s":["ag","gres","sive"],"m":"ready to attack or fight","e":"The dog was aggressive.","lv":2},
  {"w":"amateur","s":["am","a","teur"],"m":"someone who does something for fun, not money","e":"He is an amateur painter.","lv":2},
  {"w":"ancient","s":["an","cient"],"m":"very, very old","e":"We saw ancient ruins.","lv":2},
  {"w":"attached","s":["at","tached"],"m":"joined or fixed to something","e":"The note was attached to the door.","lv":2},
  {"w":"average","s":["av","er","age"],"m":"usual; the middle amount","e":"The average score was 80.","lv":2},
  {"w":"awkward","s":["awk","ward"],"m":"clumsy or uncomfortable","e":"There was an awkward silence.","lv":2},
  {"w":"bargain","s":["bar","gain"],"m":"something bought cheaply","e":"These shoes were a bargain.","lv":2},
  {"w":"bruise","s":["bruise"],"m":"a dark mark on skin after a bump","e":"I got a bruise on my knee.","lv":2},
  {"w":"cemetery","s":["cem","e","ter","y"],"m":"a place where people are buried","e":"The old cemetery is quiet.","lv":2},
  {"w":"conscious","s":["con","scious"],"m":"awake and aware","e":"He was conscious after the fall.","lv":2},
  {"w":"convenience","s":["con","ven","ience"],"m":"being easy and useful","e":"The store is open for your convenience.","lv":2},
  {"w":"correspond","s":["cor","re","spond"],"m":"to match; to write to each other","e":"Pen pals correspond by mail.","lv":2},
  {"w":"criticize","s":["crit","i","cize"],"m":"to say what is wrong with something","e":"Don't criticize your friends.","lv":2},
  {"w":"curiosity","s":["cu","ri","os","i","ty"],"m":"wanting to know things","e":"Curiosity helps you learn.","lv":2},
  {"w":"definite","s":["def","i","nite"],"m":"clear and certain","e":"We need a definite answer.","lv":2},
  {"w":"desperate","s":["des","per","ate"],"m":"needing something very badly","e":"The thirsty dog was desperate for water.","lv":2},
  {"w":"determined","s":["de","ter","mined"],"m":"not giving up","e":"She was determined to win.","lv":2},
  {"w":"disastrous","s":["dis","as","trous"],"m":"very bad; causing disaster","e":"The storm was disastrous.","lv":2},
  {"w":"equip","s":["e","quip"],"m":"to give the tools needed","e":"We equip the team with helmets.","lv":2},
  {"w":"equipped","s":["e","quipped"],"m":"having the tools needed","e":"The lab is well equipped.","lv":2},
  {"w":"existence","s":["ex","is","tence"],"m":"being real; being alive","e":"Do you believe in the existence of aliens?","lv":2},
  {"w":"foreign","s":["for","eign"],"m":"from another country","e":"She speaks a foreign language.","lv":2},
  {"w":"forty","s":["for","ty"],"m":"the number 40","e":"There are forty kids in the band.","lv":2},
  {"w":"frequently","s":["fre","quent","ly"],"m":"often","e":"It frequently rains in spring.","lv":2},
  {"w":"harass","s":["ha","rass"],"m":"to keep bothering someone","e":"Don't harass the cat.","lv":2},
  {"w":"hindrance","s":["hin","drance"],"m":"something that gets in the way","e":"The mud was a hindrance.","lv":2},
  {"w":"identity","s":["i","den","ti","ty"],"m":"who someone is","e":"The hero hid his identity.","lv":2},
  {"w":"immediate","s":["im","me","di","ate"],"m":"happening right away","e":"We need an immediate answer.","lv":2},
  {"w":"individual","s":["in","di","vid","u","al"],"m":"one single person or thing","e":"Each individual gets a prize.","lv":2},
  {"w":"interfere","s":["in","ter","fere"],"m":"to get involved when not wanted","e":"Don't interfere with my game.","lv":2},
  {"w":"interrupt","s":["in","ter","rupt"],"m":"to stop someone while they talk","e":"Please don't interrupt.","lv":2},
  {"w":"language","s":["lan","guage"],"m":"the words people use to speak","e":"English is a language.","lv":2},
  {"w":"leisure","s":["lei","sure"],"m":"free time","e":"I read in my leisure time.","lv":2},
  {"w":"lightning","s":["light","ning"],"m":"a flash of light in a storm","e":"Lightning lit up the sky.","lv":2},
  {"w":"marvelous","s":["mar","vel","ous"],"m":"wonderful","e":"What a marvelous idea!","lv":2},
  {"w":"mischievous","s":["mis","chie","vous"],"m":"playfully naughty","e":"The mischievous kitten hid my sock.","lv":2},
  {"w":"muscle","s":["mus","cle"],"m":"a body part that helps you move","e":"Exercise makes your muscles strong.","lv":2},
  {"w":"neighbor","s":["neigh","bor"],"m":"a person who lives next to you","e":"Our neighbor has a dog.","lv":2},
  {"w":"nuisance","s":["nui","sance"],"m":"something annoying","e":"The flies are a nuisance.","lv":2},
  {"w":"occupy","s":["oc","cu","py"],"m":"to fill or live in a space","e":"Books occupy the whole shelf.","lv":2},
  {"w":"occur","s":["oc","cur"],"m":"to happen","e":"When did the accident occur?","lv":2},
  {"w":"opportunity","s":["op","por","tu","ni","ty"],"m":"a good chance to do something","e":"This is a great opportunity.","lv":2},
  {"w":"parliament","s":["par","lia","ment"],"m":"a group that makes laws in the UK","e":"Parliament passed a new law.","lv":2},
  {"w":"persuade","s":["per","suade"],"m":"to talk someone into something","e":"I persuaded Dad to get a puppy.","lv":2},
  {"w":"physical","s":["phys","i","cal"],"m":"about the body","e":"Physical exercise is fun.","lv":2},
  {"w":"prejudice","s":["prej","u","dice"],"m":"an unfair opinion about someone","e":"We should stand up to prejudice.","lv":2},
  {"w":"profession","s":["pro","fes","sion"],"m":"a job that needs training","e":"Teaching is a profession.","lv":2},
  {"w":"program","s":["pro","gram"],"m":"a show; a set of instructions","e":"My favorite TV program is on.","lv":2},
  {"w":"queue","s":["queue"],"m":"a line of people waiting","e":"We stood in a queue.","lv":2},
  {"w":"recognize","s":["rec","og","nize"],"m":"to know someone you've seen before","e":"I didn't recognize you!","lv":2},
  {"w":"recommend","s":["rec","om","mend"],"m":"to suggest as good","e":"I recommend this book.","lv":2},
  {"w":"relevant","s":["rel","e","vant"],"m":"connected to what is happening","e":"Ask a relevant question.","lv":2},
  {"w":"rhyme","s":["rhyme"],"m":"words that end with the same sound","e":"Cat and hat rhyme.","lv":2},
  {"w":"rhythm","s":["rhythm"],"m":"a regular beat","e":"Clap to the rhythm.","lv":2},
  {"w":"sacrifice","s":["sac","ri","fice"],"m":"to give up something you value","e":"She made a sacrifice for her team.","lv":2},
  {"w":"secretary","s":["sec","re","tar","y"],"m":"a person who helps in an office","e":"The secretary answered the phone.","lv":2},
  {"w":"shoulder","s":["shoul","der"],"m":"where your arm joins your body","e":"The parrot sat on my shoulder.","lv":2},
  {"w":"signature","s":["sig","na","ture"],"m":"your name written by you","e":"Put your signature here.","lv":2},
  {"w":"sincere","s":["sin","cere"],"m":"honest and real","e":"She gave a sincere apology.","lv":2},
  {"w":"sincerely","s":["sin","cere","ly"],"m":"honestly; truly","e":"Yours sincerely, Tom.","lv":2},
  {"w":"soldier","s":["sol","dier"],"m":"a person in an army","e":"The soldier saluted.","lv":2},
  {"w":"stomach","s":["stom","ach"],"m":"where food goes after you eat","e":"My stomach is growling.","lv":2},
  {"w":"sufficient","s":["suf","fi","cient"],"m":"enough","e":"We have sufficient food.","lv":2},
  {"w":"suggest","s":["sug","gest"],"m":"to offer an idea","e":"I suggest we go swimming.","lv":2},
  {"w":"symbol","s":["sym","bol"],"m":"a sign that stands for something","e":"The heart is a symbol of love.","lv":2},
  {"w":"system","s":["sys","tem"],"m":"parts working together","e":"The solar system has eight planets.","lv":2},
  {"w":"thorough","s":["thor","ough"],"m":"careful and complete","e":"Do a thorough job.","lv":2},
  {"w":"twelfth","s":["twelfth"],"m":"number 12 in order","e":"Today is the twelfth of May.","lv":2},
  {"w":"variety","s":["va","ri","e","ty"],"m":"many different kinds","e":"The shop has a variety of candy.","lv":2},
  {"w":"vehicle","s":["ve","hi","cle"],"m":"something that carries people, like a car","e":"A bus is a big vehicle.","lv":2},
  {"w":"yacht","s":["yacht"],"m":"a fancy boat","e":"They sailed on a yacht.","lv":2},
  {"w":"abbreviate","s":["ab","bre","vi","ate"],"m":"tomake shorter","e":"Can you abbreviate this word?","lv":3},
  {"w":"arithmetic","s":["a","rith","me","tic"],"m":"the branch of math with numbers","e":"We learned arithmetic today.","lv":3},
  {"w":"bibliography","s":["bib","li","og","ra","phy"],"m":"a list of books used in research","e":"Check the bibliography for sources.","lv":3},
  {"w":"certificate","s":["cer","tif","i","cate"],"m":"an official document","e":"She received a certificate.","lv":3},
  {"w":"civilization","s":["civ","i","li","za","tion"],"m":"human society with cities and culture","e":"Ancient Chinese civilization was great.","lv":3},
  {"w":"conclusion","s":["con","clu","sion"],"m":"the end or finish of something","e":"In conclusion, I agree.","lv":3},
  {"w":"curriculum","s":["cur","ric","u","lum"],"m":"the subjects in a course of study","e":"Our school curriculum is challenging.","lv":3},
  {"w":"examination","s":["ex","am","i","na","tion"],"m":"a formal test","e":"The examination is on Friday.","lv":3},
  {"w":"geography","s":["ge","og","ra","phy"],"m":"the study of earth and its features","e":"We study geography in school.","lv":3},
  {"w":"hypothesis","s":["hy","poth","e","sis"],"m":"an idea that can be tested","e":"Our hypothesis needs testing.","lv":3},
  {"w":"laboratory","s":["lab","o","ra","to","ry"],"m":"a room for scientific experiments","e":"We did an experiment in the laboratory.","lv":3},
  {"w":"literature","s":["lit","er","a","ture"],"m":"written works like novels and poems","e":"We study literature in English class.","lv":3},
  {"w":"mathematics","s":["math","e","mat","ics"],"m":"the study of numbers and shapes","e":"Mathematics is my favorite subject.","lv":3},
  {"w":"measurement","s":["meas","ure","ment"],"m":"the size, length, or amount of something","e":"We took the measurement carefully.","lv":3},
  {"w":"paragraph","s":["par","a","graph"],"m":"a section of writing","e":"Start a new paragraph here.","lv":3},
  {"w":"agriculture","s":["ag","ri","cul","ture"],"m":"farming; growing crops","e":"Agriculture is important for food.","lv":3},
  {"w":"biology","s":["bi","ol","o","gy"],"m":"the study of living things","e":"We study plants in biology.","lv":3},
  {"w":"catastrophe","s":["ca","tas","tro","phe"],"m":"a sudden disaster","e":"The flood was a catastrophe.","lv":3},
  {"w":"chemistry","s":["chem","is","try"],"m":"the study of substances and how they change","e":"Chemistry is a fun subject.","lv":3},
  {"w":"contaminate","s":["con","tam","i","nate"],"m":"to make impure or polluted","e":"Don't contaminate the water.","lv":3},
  {"w":"electricity","s":["e","lec","tric","i","ty"],"m":"a form of energy for lights and machines","e":"The electricity went out.","lv":3},
  {"w":"endangered","s":["en","dan","gered"],"m":"at risk of extinction","e":"The panda is an endangered species.","lv":3},
  {"w":"evaporate","s":["e","vap","o","rate"],"m":"to change from liquid to gas","e":"The water will evaporate in the sun.","lv":3},
  {"w":"evolution","s":["ev","o","lu","tion"],"m":"the process by which living things develop","e":"Evolution takes a long time.","lv":3},
  {"w":"hibernation","s":["hi","ber","na","tion"],"m":"the state of sleeping through winter","e":"Bears go into hibernation.","lv":3},
  {"w":"hurricane","s":["hur","ri","cane"],"m":"a violent storm with strong winds","e":"The hurricane destroyed many homes.","lv":3},
  {"w":"investigation","s":["in","ves","ti","ga","tion"],"m":"a carefull examination","e":"The investigation took many days.","lv":3},
  {"w":"metamorphosis","s":["met","a","mor","pho","sis"],"m":"a major change in form","e":"The caterpillar went through metamorphosis.","lv":3},
  {"w":"microscope","s":["mi","cro","scope"],"m":"an instrument that makes small things look bigger","e":"We looked at cells under the microscope.","lv":3},
  {"w":"organism","s":["or","gan","ism"],"m":"a living thing","e":"A human is a complex organism.","lv":3},
  {"w":"photosynthesis","s":["pho","to","syn","the","sis"],"m":"how plants make food from sunlight","e":"Photosynthesis needs sunlight.","lv":3},
  {"w":"precipitation","s":["pre","cip","i","ta","tion"],"m":"rain, snow, sleet, or hail","e":"Precipitation is part of the water cycle.","lv":3},
  {"w":"vertebrate","s":["ver","te","brate"],"m":"an animal with a backbone","e":"Humans are vertebrates.","lv":3},
  {"w":"anniversary","s":["an","ni","ver","sa","ry"],"m":"a date that is remembered","e":"Today is our anniversary.","lv":3},
  {"w":"approximately","s":["ap","prox","i","mate","ly"],"m":"more or less than the exact number","e":"There are approximately 30 students.","lv":3},
  {"w":"architecture","s":["ar","chi","tec","ture"],"m":"the art of designing buildings","e":"She studies architecture.","lv":3},
  {"w":"boundary","s":["bound","a","ry"],"m":"a line that marks the limit","e":"The river is the boundary.","lv":3},
  {"w":"celebration","s":["cel","e","bra","tion"],"m":"a special event to celebrate","e":"We had a big celebration.","lv":3},
  {"w":"circumstance","s":["cir","cum","stance"],"m":"a fact or event that affects a situation","e":"Under the circumstances, it's okay.","lv":3},
  {"w":"contemporary","s":["con","tem","po","rar","y"],"m":"from the same time","e":"Contemporary art is modern.","lv":3},
  {"w":"coordinates","s":["co","or","di","nates"],"m":"numbers that show position on a map","e":"Give me the coordinates.","lv":3},
  {"w":"destination","s":["des","ti","na","tion"],"m":"the place where someone is going","e":"Our destination is the park.","lv":3},
  {"w":"expedition","s":["ex","pe","di","tion"],"m":"a journey for a specific purpose","e":"They went on an expedition.","lv":3},
  {"w":"fortunately","s":["for","tu","nate","ly"],"m":"by good luck","e":"Fortunately, no one was hurt.","lv":3},
  {"w":"headquarters","s":["head","quar","ters"],"m":"the main office of an organization","e":"The headquarters is in Beijing.","lv":3},
  {"w":"hemisphere","s":["hem","i","sphere"],"m":"half of the earth","e":"China is in the Northern Hemisphere.","lv":3},
  {"w":"horizontal","s":["hor","i","zon","tal"],"m":"going across; side to side","e":"Draw a horizontal line.","lv":3},
  {"w":"infrastructure","s":["in","fra","struc","ture"],"m":"the basic systems of a place","e":"The city needs better infrastructure.","lv":3},
  {"w":"millennium","s":["mil","len","ni","um"],"m":"a period of 1000 years","e":"We are in the third millennium.","lv":3},
  {"w":"neighborhood","s":["neigh","bor","hood"],"m":"a district where people live","e":"I live in a quiet neighborhood.","lv":3},
  {"w":"perpendicular","s":["per","pen","dic","u","lar"],"m":"forming a right angle","e":"The lines are perpendicular.","lv":3},
  {"w":"surveillance","s":["sur","veil","lance"],"m":"careful watch kept over someone or something","e":"The police use surveillance cameras.","lv":3},
  {"w":"topography","s":["to","pog","ra","phy"],"m":"the shape and features of the land","e":"The topography of the mountains is steep.","lv":3},
  {"w":"vicinity","s":["vi","cin","i","ty"],"m":"the area near a place","e":"Is there a store in the vicinity?","lv":3},
  {"w":"wilderness","s":["wil","der","ness"],"m":"a wild, uncultivated region","e":"They hiked into the wilderness.","lv":3},
  {"w":"calculate","s":["cal","cu","late"],"m":"to find an answer using math","e":"Calculate the total cost.","lv":3},
  {"w":"collaborate","s":["col","lab","o","rate"],"m":"to work together on something","e":"Let's collaborate on this project.","lv":3},
  {"w":"consequence","s":["con","se","quence"],"m":"a result of an action","e":"Think about the consequences.","lv":3},
  {"w":"demonstrate","s":["dem","on","strate"],"m":"to show how something works","e":"Can you demonstrate the machine?","lv":3},
  {"w":"distribute","s":["dis","trib","ute"],"m":"to give out to several people","e":"Distribute the papers to everyone.","lv":3},
  {"w":"efficiency","s":["ef","fi","cien","cy"],"m":"doing things without waste","e":"The new system improves efficiency.","lv":3},
  {"w":"eliminate","s":["e","lim","i","nate"],"m":"to remove completely","e":"We must eliminate the errors.","lv":3},
  {"w":"enthusiastic","s":["en","thu","si","as","tic"],"m":"showing strong excitement","e":"She is enthusiastic about reading.","lv":3},
  {"w":"equivalent","s":["e","quiv","a","lent"],"m":"equal in value or meaning","e":"One dollar is equivalent to 100 cents.","lv":3},
  {"w":"evaluate","s":["e","val","u","ate"],"m":"to judge the value of something","e":"The teacher will evaluate your work.","lv":3},
  {"w":"evidence","s":["ev","i","dence"],"m":"facts that prove something","e":"There is evidence of life on Mars.","lv":3},
  {"w":"exception","s":["ex","cep","tion"],"m":"something that does not follow a rule","e":"Everyone came, with one exception.","lv":3},
  {"w":"navigate","s":["nav","i","gate"],"m":"to find your way","e":"Can you navigate through the forest?","lv":3},
  {"w":"obstacle","s":["ob","sta","cle"],"m":"something that blocks your way","e":"Fear is a big obstacle to success.","lv":3},
  {"w":"perspective","s":["per","spec","tive"],"m":"a way of thinking about something","e":"Try to see it from my perspective.","lv":3},
  {"w":"phenomenon","s":["phe","nom","e","non"],"m":"something that happens in nature","e":"A rainbow is a natural phenomenon.","lv":3},
  {"w":"absolute","s":["ab","so","lute"],"m":"complete and total","e":"He has absolute power.","lv":4},
  {"w":"academic","s":["ac","a","dem","ic"],"m":"relating to education","e":"She has academic talent.","lv":4},
  {"w":"accumulate","s":["ac","cu","mu","late"],"m":"to gather over time","e":"Dust accumulates on shelves.","lv":4},
  {"w":"accurate","s":["ac","cu","rate"],"m":"correct and exact","e":"Give me an accurate answer.","lv":4},
  {"w":"adequate","s":["ad","e","quate"],"m":"enough for a purpose","e":"We have adequate food.","lv":4},
  {"w":"admission","s":["ad","mis","sion"],"m":"permission to enter","e":"Admission to the museum is free.","lv":4},
  {"w":"advantage","s":["ad","van","tage"],"m":"something that helps you","e":"Height is an advantage in basketball.","lv":4},
  {"w":"advertise","s":["ad","ver","tise"],"m":"to promote a product","e":"They advertise on TV.","lv":4},
  {"w":"advocate","s":["ad","vo","cate"],"m":"to support a cause","e":"She advocates for animal rights.","lv":4},
  {"w":"allocate","s":["al","lo","cate"],"m":"to distribute for a purpose","e":"We allocate funds for research.","lv":4},
  {"w":"ambiguous","s":["am","big","u","ous"],"m":"having more than one meaning","e":"His answer was ambiguous.","lv":4},
  {"w":"analyze","s":["an","a","lyze"],"m":"to study carefully","e":"Scientists analyze the data.","lv":4},
  {"w":"ancestor","s":["an","ces","tor"],"m":"a family member from the past","e":"My ancestors came from Italy.","lv":4},
  {"w":"anticipate","s":["an","tic","i","pate"],"m":"to expect something","e":"We anticipate rain tomorrow.","lv":4},
  {"w":"appropriate","s":["ap","pro","pri","ate"],"m":"suitable for the situation","e":"Wear appropriate clothes.","lv":4},
  {"w":"arrangement","s":["ar","range","ment"],"m":"a plan or organization","e":"We made arrangements for the trip.","lv":4},
  {"w":"assemble","s":["as","sem","ble"],"m":"to put together","e":"We assemble the parts here.","lv":4},
  {"w":"assembly","s":["as","sem","bly"],"m":"a gathering of people","e":"The school assembly starts at nine.","lv":4},
  {"w":"assignment","s":["as","sign","ment"],"m":"a task given to someone","e":"Finish your homework assignment.","lv":4},
  {"w":"assistance","s":["as","sis","tance"],"m":"help or support","e":"Can I offer assistance?","lv":4},
  {"w":"assumption","s":["as","sump","tion"],"m":"something taken as true without proof","e":"Your assumption is wrong.","lv":4},
  {"w":"attachment","s":["at","tach","ment"],"m":"something fixed to something else","e":"Send the file as an attachment.","lv":4},
  {"w":"attendance","s":["at","tend","ance"],"m":"the act of being present","e":"Attendance is mandatory.","lv":4},
  {"w":"attraction","s":["at","trac","tion"],"m":"something that draws interest","e":"The zoo is a popular attraction.","lv":4},
  {"w":"authority","s":["au","thor","i","ty"],"m":"the power to command","e":"The manager has authority over the team.","lv":4},
  {"w":"awareness","s":["a","ware","ness"],"m":"knowledge of something","e":"Raise awareness about safety.","lv":4},
  {"w":"behavior","s":["be","hav","ior"],"m":"the way someone acts","e":"His behavior was strange.","lv":4},
  {"w":"beneficiary","s":["ben","e","fi","ci","a","ry"],"m":"someone who receives benefits","e":"She is the beneficiary of the trust.","lv":4},
  {"w":"candidate","s":["can","di","date"],"m":"a person seeking a position","e":"He is a strong candidate.","lv":4},
  {"w":"capacity","s":["ca","pac","i","ty"],"m":"the maximum amount something can hold","e":"The stadium has a large capacity.","lv":4},
  {"w":"carrier","s":["car","ri","er"],"m":"a person or thing that carries","e":"The airline is a major carrier.","lv":4},
  {"w":"classify","s":["clas","si","fy"],"m":"to sort into groups","e":"Scientists classify living things.","lv":4},
  {"w":"commentary","s":["com","men","tar","y"],"m":"spoken remarks about an event","e":"The commentary on the game was exciting.","lv":4},
  {"w":"commission","s":["com","mis","sion"],"m":"a group chosen to do something","e":"The commission will investigate.","lv":4},
  {"w":"commodity","s":["com","mod","i","ty"],"m":"a raw material or product","e":"Oil is an important commodity.","lv":4},
  {"w":"companion","s":["com","pan","ion"],"m":"a person who accompanies you","e":"My dog is my best companion.","lv":4},
  {"w":"comparison","s":["com","par","i","son"],"m":"the act of comparing","e":"There is no comparison between them.","lv":4},
  {"w":"component","s":["com","po","nent"],"m":"a part of something","e":"Each component is important.","lv":4},
  {"w":"compromise","s":["com","pro","mise"],"m":"a settlement of differences","e":"We reached a compromise.","lv":4},
  {"w":"concentrate","s":["con","cen","trate"],"m":"to focus attention","e":"I cannot concentrate with noise.","lv":4},
  {"w":"consensus","s":["con","sen","sus"],"m":"general agreement","e":"We reached a consensus.","lv":4},
  {"w":"construction","s":["con","struc","tion"],"m":"the act of building","e":"The construction is ongoing.","lv":4},
  {"w":"consultant","s":["con","sul","tant"],"m":"an expert who gives advice","e":"She hired a business consultant.","lv":4},
  {"w":"consumer","s":["con","su","mer"],"m":"a person who buys things","e":"Consumer prices went up.","lv":4},
  {"w":"container","s":["con","tain","er"],"m":"something that holds things","e":"Put it in a plastic container.","lv":4},
  {"w":"continent","s":["con","ti","nent"],"m":"a large land mass","e":"Africa is a vast continent.","lv":4},
  {"w":"contradiction","s":["con","tra","dic","tion"],"m":"a statement that conflicts with another","e":"That is a clear contradiction.","lv":4},
  {"w":"contribute","s":["con","trib","ute"],"m":"to give or help","e":"Everyone should contribute.","lv":4},
  {"w":"corporation","s":["cor","po","ra","tion"],"m":"a large business","e":"He works for a big corporation.","lv":4},
  {"w":"corporate","s":["cor","po","rate"],"m":"relating to a business","e":"They have a corporate logo.","lv":4},
  {"w":"correlation","s":["cor","re","la","tion"],"m":"a connection between things","e":"There is a correlation between exercise and health.","lv":4},
  {"w":"creation","s":["cre","a","tion"],"m":"something made","e":"The creation of the world.","lv":4},
  {"w":"critical","s":["crit","i","cal"],"m":"very important","e":"This is a critical moment.","lv":4},
  {"w":"cultural","s":["cul","tur","al"],"m":"relating to culture","e":"We study cultural traditions.","lv":4},
  {"w":"currency","s":["cur","ren","cy"],"m":"the money of a country","e":"What is the local currency?","lv":4},
  {"w":"declaration","s":["dec","la","ra","tion"],"m":"a formal statement","e":"They signed a declaration.","lv":4},
  {"w":"dedicate","s":["ded","i","cate"],"m":"to devote to a purpose","e":"She dedicated her life to science.","lv":4},
  {"w":"democracy","s":["de","moc","ra","cy"],"m":"government by the people","e":"We live in a democracy.","lv":4},
  {"w":"department","s":["de","part","ment"],"m":"a division of an organization","e":"She works in the sales department.","lv":4},
  {"w":"dependent","s":["de","pend","ent"],"m":"needing someone or something","e":"Children are dependent on parents.","lv":4},
  {"w":"deposit","s":["de","pos","it"],"m":"money placed in a bank","e":"I need to make a deposit.","lv":4},
  {"w":"designer","s":["de","sign","er"],"m":"a person who creates things","e":"She is a fashion designer.","lv":4},
  {"w":"devotion","s":["de","vo","tion"],"m":"loyalty and love","e":"Her devotion to her family is strong.","lv":4},
  {"w":"dialogue","s":["di","a","logue"],"m":"conversation between people","e":"The dialogue was amusing.","lv":4},
  {"w":"diploma","s":["di","plo","ma"],"m":"a certificate of graduation","e":"She received her diploma.","lv":4},
  {"w":"directory","s":["di","rec","to","ry"],"m":"a list of names or files","e":"Check the phone directory.","lv":4},
  {"w":"discussion","s":["dis","cus","sion"],"m":"a talk about something","e":"We had a long discussion.","lv":4},
  {"w":"disposal","s":["dis","pos","al"],"m":"the act of getting rid of","e":"Put waste in the disposal bin.","lv":4},
  {"w":"division","s":["di","vi","sion"],"m":"the act of separating","e":"The division of the land was unfair.","lv":4},
  {"w":"domestic","s":["do","mes","tic"],"m":"relating to home or country","e":"Domestic flights are cheaper.","lv":4},
  {"w":"dominant","s":["dom","i","nant"],"m":"most important or powerful","e":"English is the dominant language.","lv":4},
  {"w":"economy","s":["e","con","o","my"],"m":"the system of money and trade","e":"The economy is improving.","lv":4},
  {"w":"educator","s":["ed","u","ca","tor"],"m":"a person who teaches","e":"She is a dedicated educator.","lv":4},
  {"w":"effective","s":["ef","fec","tive"],"m":"producing a result","e":"This method is effective.","lv":4},
  {"w":"efficient","s":["ef","fi","cient"],"m":"working without waste","e":"She is an efficient worker.","lv":4},
]
